---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

