apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  labels:
    app.kubernetes.io/name: loki-stack
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: observability
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    description: "Loki and Promtail for log aggregation and collection"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.1
    helm:
      releaseName: loki-stack
      values: |
        loki:
          enabled: true
          # Horizontal Pod Autoscaler for Loki
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 5
            targetCPUUtilizationPercentage: 70
            targetMemoryUtilizationPercentage: 80
          persistence:
            enabled: true
            size: 100Gi
            # Using Azure Blob Storage for chunks (cost-optimized vs premium disk)
            # Premium disk only for WAL (write-ahead log) if needed
            storageClassName: managed-csi  # Standard storage for cost optimization
          config:
            storage_config:
              azure:
                account_name: ${AZURE_STORAGE_ACCOUNT}
                account_key: ${AZURE_STORAGE_KEY}
                container_name: loki-chunks
            # Cost optimization: Limit retention
            limits_config:
              retention_period: 15d  # 15 days retention (cost-optimized)
            # Compaction for cost savings
            compactor:
              retention_enabled: true
              retention_delete_delay: 2h
              retention_delete_worker_count: 150
        
        promtail:
          enabled: true
          # Horizontal Pod Autoscaler for Promtail
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 10
            targetCPUUtilizationPercentage: 70
          config:
            clients:
              - url: http://loki:3100/loki/api/v1/push
            # Cost optimization: Batch configuration
            batchwait: 1s
            batchsize: 1048576  # 1MB batches for efficiency
        
        grafana:
          enabled: false  # Already deployed in prometheus-stack

  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m