apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster
  namespace: argocd
  labels:
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/component: message-broker
    app.kubernetes.io/part-of: middleware
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    description: "RabbitMQ message broker cluster"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: middleware
  source:
    chart: rabbitmq-cluster-operator
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.11.1
    helm:
      releaseName: rabbitmq
      values: |
        replicaCount: 3
        
        auth:
          username: admin
          existingPasswordSecret: rabbitmq-credentials
          existingErlangSecret: rabbitmq-erlang-cookie
        
        # Horizontal Pod Autoscaler for RabbitMQ
        autoscaling:
          enabled: true
          minReplicas: 3
          maxReplicas: 6  # Limit max for cost control
          targetCPUUtilizationPercentage: 70
          targetMemoryUtilizationPercentage: 80
        
        persistence:
          enabled: true
          storageClass: managed-csi-premium  # Premium for stateful message broker
          size: 50Gi  # Right-sized based on message volume
        
        resources:
          requests:
            memory: 2Gi
            cpu: 1000m
          limits:
            memory: 4Gi
            cpu: 2000m
        
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        
        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: rabbitmq.yourdomain.com
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          tls: true

  destination:
    server: https://kubernetes.default.svc
    namespace: middleware
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m