apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster
  namespace: argocd
  labels:
    app.kubernetes.io/name: redis-cluster
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: middleware
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    description: "Redis cluster for caching and session storage"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: middleware
  source:
    chart: redis-cluster
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.5.1
    helm:
      releaseName: redis
      values: |
        cluster:
          nodes: 6
          replicas: 1
        
        persistence:
          enabled: true
          storageClass: managed-csi-premium
          size: 20Gi
        
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1000m
        
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        
        usePassword: true
        existingSecret: redis-credentials

  destination:
    server: https://kubernetes.default.svc
    namespace: middleware
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m