apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster
  namespace: argocd
spec:
  project: middleware
  source:
    chart: redis-cluster
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.5.1
    helm:
      releaseName: redis
      values: |
        cluster:
          nodes: 6
          replicas: 1
        
        persistence:
          enabled: true
          storageClass: managed-csi-premium
          size: 20Gi
        
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
          limits:
            memory: 2Gi
            cpu: 1000m
        
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        
        usePassword: true
        existingSecret: redis-credentials

  destination:
    server: https://kubernetes.default.svc
    namespace: middleware
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true