apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
  labels:
    app.kubernetes.io/name: istio-ingressgateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: istio
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    description: "Istio Ingress Gateway for external traffic"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.20.1
    helm:
      releaseName: istio-ingressgateway
      values: |
        labels:
          istio: ingressgateway
        
        replicaCount: 3
        
        autoscaling:
          enabled: true
          minReplicas: 3
          maxReplicas: 10
          targetCPUUtilizationPercentage: 80
          targetMemoryUtilizationPercentage: 80  # Add memory target for better scaling
          behavior:
            scaleDown:
              stabilizationWindowSeconds: 300  # 5 min cooldown before scaling down
              policies:
                - type: Percent
                  value: 50
                  periodSeconds: 60
            scaleUp:
              stabilizationWindowSeconds: 0  # Fast scale-up for traffic spikes
              policies:
                - type: Percent
                  value: 100
                  periodSeconds: 15
        
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 1024Mi
        
        service:
          type: LoadBalancer
          ports:
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
          
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "false"
            service.beta.kubernetes.io/azure-pip-name: "aks-ingress-pip"
        
        # Pod annotations for Prometheus scraping
        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "15020"
          prometheus.io/path: "/stats/prometheus"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m