using IdentityService.Application.Common.Interfaces;
using IdentityService.Domain.Interfaces;
using Microsoft.Extensions.Logging;

namespace IdentityService.Infrastructure.Services.MfaProviders;

/// <summary>
/// TOTP MFA provider implementation
/// </summary>
public class TotpMfaProvider : IMfaProvider
{
    public string ProviderType => "TOTP";

    private readonly IMfaFactorRepository _mfaFactorRepository;
    private readonly ITotpService _totpService;
    private readonly ILogger<TotpMfaProvider> _logger;

    public TotpMfaProvider(
        IMfaFactorRepository mfaFactorRepository,
        ITotpService totpService,
        ILogger<TotpMfaProvider> logger)
    {
        _mfaFactorRepository = mfaFactorRepository;
        _totpService = totpService;
        _logger = logger;
    }

    public Task<string> GenerateCodeAsync(
        Guid userId,
        string identifier,
        CancellationToken cancellationToken = default)
    {
        // TOTP codes are generated by the authenticator app, not by us
        // This method is not applicable for TOTP
        throw new NotSupportedException("TOTP codes are generated by the authenticator app");
    }

    public Task<bool> SendCodeAsync(
        Guid userId,
        string identifier,
        string code,
        CancellationToken cancellationToken = default)
    {
        // TOTP codes are not sent, they're generated by the authenticator app
        throw new NotSupportedException("TOTP codes are not sent, they are generated by the authenticator app");
    }

    public async Task<bool> VerifyCodeAsync(
        Guid userId,
        string identifier,
        string code,
        CancellationToken cancellationToken = default)
    {
        try
        {
            // Get TOTP factor for user
            var factor = await _mfaFactorRepository.GetEnabledTotpFactorByUserIdAsync(userId, cancellationToken);
            if (factor == null || !factor.IsEnabled)
            {
                return false;
            }

            // Verify TOTP code
            var isValid = _totpService.ValidateCode(factor.Secret, code);

            if (isValid)
            {
                factor.RecordUsage();
                await _mfaFactorRepository.UpdateAsync(factor, cancellationToken);
            }

            return isValid;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error verifying TOTP code");
            return false;
        }
    }
}

